from importlib.metadata import PackageNotFoundError, version

from buildaquery.compiler import (
    CockroachDbCompiler,
    ClickHouseCompiler,
    CompiledQuery,
    DuckDbCompiler,
    MariaDbCompiler,
    MsSqlCompiler,
    MySqlCompiler,
    OracleCompiler,
    PostgresCompiler,
    SqliteCompiler,
)
from buildaquery.execution import (
    CockroachExecutor,
    ClickHouseExecutor,
    ConnectionSettings,
    ConnectionTimeoutError,
    DeadlockError,
    DuckDbExecutor,
    ExecutorCapabilities,
    ExecutionError,
    ExecutionEvent,
    InMemoryMetricsAdapter,
    InMemoryTracingAdapter,
    IntegrityConstraintError,
    LockTimeoutError,
    MariaDbExecutor,
    MetricPoint,
    MsSqlExecutor,
    MySqlExecutor,
    ObservabilitySettings,
    OracleExecutor,
    PostgresExecutor,
    ProgrammingExecutionError,
    QueryObservation,
    RetryPolicy,
    SerializationError,
    SqliteExecutor,
    TraceEvent,
    TraceSpan,
    TransientExecutionError,
    compose_event_observers,
    execution_event_to_dict,
    make_json_event_logger,
)

try:
    __version__ = version("buildaquery")
except PackageNotFoundError:
    __version__ = "0.0.0"

__all__ = [
    "__version__",
    "PostgresCompiler",
    "SqliteCompiler",
    "MySqlCompiler",
    "MariaDbCompiler",
    "CockroachDbCompiler",
    "ClickHouseCompiler",
    "DuckDbCompiler",
    "OracleCompiler",
    "MsSqlCompiler",
    "CompiledQuery",
    "PostgresExecutor",
    "SqliteExecutor",
    "MySqlExecutor",
    "MariaDbExecutor",
    "CockroachExecutor",
    "ClickHouseExecutor",
    "DuckDbExecutor",
    "OracleExecutor",
    "MsSqlExecutor",
    "RetryPolicy",
    "ExecutorCapabilities",
    "ConnectionSettings",
    "ObservabilitySettings",
    "QueryObservation",
    "ExecutionEvent",
    "TraceEvent",
    "TraceSpan",
    "MetricPoint",
    "InMemoryMetricsAdapter",
    "InMemoryTracingAdapter",
    "compose_event_observers",
    "execution_event_to_dict",
    "make_json_event_logger",
    "ExecutionError",
    "TransientExecutionError",
    "DeadlockError",
    "SerializationError",
    "LockTimeoutError",
    "ConnectionTimeoutError",
    "IntegrityConstraintError",
    "ProgrammingExecutionError",
]
